job/Jobs/Api/urls.py
from django.urls import path 
from .views import *

app_name='Jobs'

urlpatterns = [
   path('jobs_list',api_list_job.as_view() ,name="jobs_list"),
   path('jobs_detalis/<slug>' ,api_detail_job.as_view() , name='job_detail'),
   path('jobs_detalis/<slug>/update' , api_edit_job.as_view() , name="update_job"),
   path('jobs_detalis/<slug>/delete' , api_delete_job.as_view() , name="delete_job"),
   path('api_category_create' , api_create_category.as_view() , name="create_category"),
   path('api_job_create' , api_create_job.as_view() , name="api_job_create"),

]

job/Jobs/urls.py
from django.urls import path 
from . import views


app_name='Jobs'

urlpatterns = [
   
    path('', views.job_list, name='job_list'),
    path('add', views.add_job, name='add_job'),
    path('<str:slug>' , views.job_detail,name='job_detail'),
 
]

job/job/urls.py
from django.contrib import admin 
from django.urls import path , include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    

    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/',include('accounts.urls',namespace='accounts') ),
    path('admin/', admin.site.urls),
    path('jobs/', include('Jobs.urls', namespace='jobs')),
    path('contact_us/', include('Contact.urls', namespace='contact_us')),
    path('weather/', include('Weather.urls', namespace='weather')),

    path('',include('Home.urls',namespace='home') ),

    #REST FRAMEWORK URLS
    path('api-auth/', include('rest_framework.urls')),
    path('api/',include('Jobs.Api.urls' , namespace='api')),
   
    
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

job/Jobs/models.py
from django.db import models

# Create your models here.
from django.db import models
from django.utils.text import slugify
from django import forms
from django.contrib.auth.models import User
from accounts.models import Compaine

# Create your models here.

Job_type = (

    ('full time' , 'full time'),
    ('part time' , 'part time'),

)

def image_upload(instance,filename):
    imagename , extension = filename.split(".")
    return "jobs/%s/%s.%s"%(instance.id,instance.id,extension)
    

class job(models.Model):

    owner = models.ForeignKey(User, related_name ='job_owner', on_delete =models.CASCADE)
    title = models.CharField( max_length=100) 
    job_type = models.CharField(max_length=15, choices=Job_type , null=True)
    discrpations = models.TextField(max_length=1000 , null=True)
    published_at = models.DateTimeField(auto_now=True)
    vacancy = models.IntegerField(default=1 , null=True)
    salary = models.IntegerField(default=0 , null=True)
    experience = models.IntegerField(default=1 , null=True)
    category = models.ForeignKey('Category' , on_delete=models.CASCADE)
    image = models.ImageField(upload_to=image_upload )
    companie = models.ForeignKey(Compaine, related_name='job_companie', verbose_name="companie name", on_delete=models.CASCADE)

    slug = models.SlugField(blank=True,null=True)



    def save(self,*args,**kwargs):
        self.slug  = slugify(self.title)
        super(job,self).save(*args,**kwargs)
    


    def __str__(self):
        return self.title


class Category (models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name


class Apply(models.Model):
   
    job = models.ForeignKey(job, related_name= 'apply_job', on_delete= models.CASCADE)
    name = models.CharField(max_length=50)
    email = models.EmailField(max_length=100)
    website =  models.URLField(max_length = 200 ,null=True) 
    cv = models.FileField(upload_to='apply/')
    cover_letter = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.name
    
            
        

job/Jobs/Api/views.py
from Jobs.Api.serializers import *
from Jobs.models import *
from django.shortcuts import get_object_or_404
from rest_framework import generics
from .permissions import IsOwnerOrReadOnly
from rest_framework.filters import SearchFilter , OrderingFilter
from .pagination import PostPageNumberPagination , PostLimitOffsetPagination

from rest_framework.permissions import IsAuthenticated , AllowAny , IsAuthenticatedOrReadOnly , IsAdminUser


# @api_view(['GET'])
# def jobsListApi(request):

#     try:
#        all_jobs = job.objects.all()
#        data = JobsSerializers(all_jobs, many=True).data
#        return Response({'data':data})
#     except job.DoesNotExist:
#         return Response(status= status.HTTP_404_NOT_FOUND)

# # @api_view(['GET'])
# def job_details(request, slug):
#     try:
#        job_detail = job.objects.get(slug=slug)
#     except job.DoesNotExist:
#         return Response(status= status.HTTP_404_NOT_FOUND)

#     if request.method == "GET" : 
#         data = JobsSerializers(job_detail).data
#         return Response({'data' :data})


# @api_view(['PUT'])
# def job_update(request, slug):
#     try:
#        job_detail = job.objects.get(slug=slug)
#     except job.DoesNotExist:
#         return Response(status= status.HTTP_404_NOT_FOUND)

#     if request.method == "PUT" : 
#         serializer = JobsSerializers(job_detail , data=request.data)
#         data = {}
#         if serializer.is_valid():
#             serializer.save()
#             data["success"] = "Update Successfuly"
#         return Response({'data' :data})
#     return Response(serializers.errors, status=status.HTTP_404_NOT_FOUND)    


# @api_view(['DELETE'])
# def job_delete(request, slug):
#     try:
#        job_detail = job.objects.get(slug=slug)
#     except job.DoesNotExist:
#         return Response(status=status.HTTP_404_NOT_FOUND)

#     if request.method == "DELETE" : 
#         operation = job_detail.delete()
#         data = {}
#         if operation:
#             data["success"] = "delete successful"
#         else:
#             data["success"] = "delete faild"    
#     return Response(data = data)    

# List ALl job API 
class api_list_job(generics.ListAPIView):
    queryset = job.objects.all()
    serializer_class = JobSerializerList
    filter_backends = [SearchFilter , OrderingFilter]
    search_fields = ['title' , 'owner' , 'job_type']
    pagination_class = PostPageNumberPagination
# Create Job API
class api_create_job(generics.CreateAPIView):
    queryset = job.objects.all()
    serializer_class = JobSerializerCreate
    permission_classes = [IsAuthenticated ]

    # To Associate User : the owner who make a request
    def perform_create(self, serializer):
        serializer.save(owner=self.request.user.id)


# View Job detail API    
class api_detail_job(generics.RetrieveAPIView):
    queryset = job.objects.all()
    serializer_class = JobSerializerDetails
    permission_classes = [IsAuthenticated ]
    # this because i use slug
    lookup_field = 'slug'


# Edit Job APi 
class api_edit_job(generics.RetrieveUpdateAPIView):
    queryset = job.objects.all()
    serializer_class = JobSerializerUpdate
    lookup_field = 'slug'
    permission_classes = [IsAuthenticated , IsOwnerOrReadOnly]


    # to add delete button in that page 
    def delete(self,request,slug):
        queryset = get_object_or_404(job,slug=slug)
        queryset.delete()

# Delete Job
class api_delete_job(generics.DestroyAPIView):
    queryset = job.objects.all()
    serializer_class = JobSerializerDelete
    lookup_field = 'slug'
# Create Category API


class api_create_category(generics.CreateAPIView):
    serializer_class = CategorySerializers
    def get_queryset(self):
        return Category.objects.all()



# @api_view(['POST'])
# def api_category_create(request):
   
#    if request.method == "POST":
#        data={}
#        serializer = CategorySerializers( data=request.data)
#        if serializer.is_valid():
#            serializer.save()
#            data["success"] = "Created"
#            return Response({'data':data}) 
        

job/Jobs/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required

from django.shortcuts import render , redirect
from .models import *
from django.template import Context
from django.core.paginator import Paginator
from .form import ApplyForm ,JobForm
from django.urls import reverse
from .filters import JobFilter 

# Create your views here.

def job_list(request):
    all_jobs_list = job.objects.all()
    
    # Filters for Job in home page 
    myfilter = JobFilter(request.GET , queryset = all_jobs_list)
    all_jobs_list = myfilter.qs
    paginator = Paginator(all_jobs_list,4) # Show 25 contacts per page.
    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)

    context = {'all_job' : page_obj , 'myfilter' :myfilter}

    return render(request,'job/job_list.html',context)


def job_detail(request, slug):
    job_detail = job.objects.get(slug=slug)

    if request.method=='POST':
        form = ApplyForm(request.POST , request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)  
            myform.job =  job_detail
            myform.save()  
            return redirect(reverse('Jobs:job_detail'))   

    else:
        form = ApplyForm()         

    context = {'job' : job_detail , 'form' : ApplyForm}
    return render(request,'job/job_detail.html',context)

@login_required
def add_job(request):

    if request.method=='POST':
        form = JobForm(request.POST , request.FILES)
        if form.is_valid():
            myform = form.save(commit=False)
            myform.owner = request.user
            myform.save() 
            return redirect(reverse('Jobs:job_list'))
    else:
        form = JobForm()    
    
    return render(request,'job/add_job.html',{'form':form})

job/Jobs/templates/job/add_job.html
{% extends 'base.html' %}
 {% load bootstrap4 %} 

{% block body %}
<!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>Add New Job !</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-10 mx-auto">
                    
                    <div class="apply_job_form white-bg">
                        <h4>Post New Job </h4>
                        <form  method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% buttons %}
                            <button class="boxed-btn3 w-100" type="submit">Post Now</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
               
            </div>
        </div>
    </div>

{% endblock body %}
    



    

job/Jobs/templates/job/job_detail.html
{% extends 'base.html' %}
 {% load bootstrap4 %} 

{% block body %}
<!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{job.title}}</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <div class="job_details_area">
        <div class="container">
            <div class="row">
                <div class="col-lg-8">
                    <div class="job_details_header">
                        <div class="single_jobs white-bg d-flex justify-content-between">
                            <div class="jobs_left d-flex align-items-center">
                                <div class="thumb">
                                    <img src="{{job.image.url}}" alt="" style="width: 82px; height:82px">
                                </div>
                                <div class="jobs_conetent">
                                    <a href="#"><h4>{{job.title}}</h4></a>
                                    <div class="links_locat d-flex align-items-center">
                                        <div class="location">
                                            <p> <i class="fa fa-map-marker"></i> {{job.companie.name}}</p>
                                        </div>
                                        <div class="location">
                                            <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="jobs_right">
                                <div class="apply_now">
                                    <a class="heart_mark" href="#"> <i class="ti-heart"></i> </a>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="descript_wrap white-bg">
                        <div class="single_wrap">
                            <h4>Job description</h4>
                            <p>{{job.discrations}}</p>

                        </div>
                        
                    </div>
                    <div class="apply_job_form white-bg">
                        <h4>Apply for the job</h4>
                        <form  method="POST" enctype="multipart/form-data">
                            {% csrf_token %}
                            {% bootstrap_form form %}
                            {% buttons %}
                            <button class="boxed-btn3 w-100" type="submit">Apply Now</button>
                            {% endbuttons %}
                        </form>
                    </div>
                </div>
                <div class="col-lg-4">
                    <div class="job_sumary">
                        <div class="summery_header">
                            <h3>Job Summery</h3>
                        </div>
                        <div class="job_content">
                            <ul>
                                <li>Published on: <span>{{job.published_at|date:'d M o'}}</span></li>
                                <li>Vacancy: <span>{{job.vacancy}}</span></li>
                                <li>Salary: <span>{{job.salary}}k/y</span></li>
                                <li>Location: <span>{{job.companie.name}}</span></li>
                                <li>Job Nature: <span> {{job.job_type}}</span></li>
                            </ul>
                        </div>
                    </div>
                    <div class="share_wrap d-flex">
                        <span>Share at:</span>
                        <ul>
                            <li><a href="#"> <i class="fa fa-facebook"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-google-plus"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-twitter"></i></a> </li>
                            <li><a href="#"> <i class="fa fa-envelope"></i></a> </li>
                        </ul>
                    </div>
                   
                </div>
            </div>
        </div>
    </div>

{% endblock body %}
    



    

job/Jobs/templates/job/job_list.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block body  %}
    
    
    <!-- bradcam_area  -->
    <div class="bradcam_area bradcam_bg_1">
        <div class="container">
            <div class="row">
                <div class="col-xl-12">
                    <div class="bradcam_text">
                        <h3>{{all_job.count}}+ Jobs Available</h3>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--/ bradcam_area  -->

    <!-- job_listing_area_start  -->
    <div class="job_listing_area plus_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="job_filter white-bg">
                        <div class="form_inner white-bg">
                            <h3>Filter</h3>
                            <form method="GET">
                                {% bootstrap_form myfilter.form %}
                                <input  class="boxed-btn3 w-100 mt-2" type="submit" value="Search"> 
                            </form>
                        </div>
                        
                        
                           
                        
                    </div>
                </div>
                <div class="col-lg-9">
                    <div class="recent_joblist_wrap">
                        <div class="recent_joblist white-bg ">
                            <div class="row align-items-center">
                                <div class="col-md-6">
                                    <h4>Job Listing</h4>
                                </div>
                                
                            </div>
                        </div>
                    </div>

                    <div class="job_lists m-0">
                        <div class="row">

                        {% for job in all_job %}
                            <div class="col-lg-12 col-md-12">
                                <div class="single_jobs white-bg d-flex justify-content-between">
                                    <div class="jobs_left d-flex align-items-center">
                                        <div class="thumb">
                                            <img src="{{job.image.url}}" alt="" style="width:82px; height:82px"> 
                                        </div>
                                        <div class="jobs_conetent">
                                            <a href="{% url 'jobs:job_detail' job.slug%}"><h4>{{job.title}}</h4></a>
                                            <div class="links_locat d-flex align-items-center">
                                               
                                                <div class="location">
                                                    <p> <i class="fa fa-clock-o"></i> {{job.job_type}}</p>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                    <div class="jobs_right">
                                        <div class="apply_now">
                                            
                                            <a href="{% url 'jobs:job_detail' job.slug%}" class="boxed-btn3">Apply Now</a>
                                        </div>
                                        <div class="date">
                                            <p>Date line: {{job.published_at|date:'d M o'}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        {% endfor %}  

                        </div>
                        {% if all_job.has_other_pages %}
                        
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="pagination_wrap">
                                        <ul>

                                        {% if all_job.has_previous %}
                                            <li><a href="?page={{all_job.previous_page_number}}"> <i class="ti-angle-left"></i> </a></li>
                                        {% endif %}

                                            {% for i in all_job.paginator.page_range  %}
                                                <li><a href="?page={{i}}"><span>{{i}}</span></a></li>
                                            {% endfor %}
                                        
                                            
                                        {% if all_job.has_next %}
                                            <li><a href="?page={{all_job.next_page_number}}"> <i class="ti-angle-right"></i> </a></li>
                                        {% endif %}
                                        
                                        </ul>
                                    </div>
                                </div>
                            </div>

                        {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!-- job_listing_area_end  -->
    
{% endblock body %}
   